version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ecommerce_postgres
    environment:
      POSTGRES_DB: SpringBootDP
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Yogesh#1409"
    ports:
      - "5432:5432"
    networks:
      - ecommerce-net

  app:
    build: .
    container_name: ecommerce_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/SpringBootDP
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "Yogesh#1409"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
